[tool.poetry]
name = "openweathermapapi"
version = "0.1.0"
description = ""
authors = ["Maksim Kachur <me@maksimkachur.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
